python tfold_rush_solver.py 511 || true 
python tfold_rush_solver.py 513 || true 
python tfold_rush_solver.py 514 || true 
python tfold_rush_solver.py 516 || true 
python tfold_rush_solver.py 519 || true 
python tfold_rush_solver.py 524 || true 
python tfold_rush_solver.py 527 || true 
python tfold_rush_solver.py 531 || true 
python tfold_rush_solver.py 533 || true 
python tfold_rush_solver.py 534 || true 
python tfold_rush_solver.py 535 || true 
python tfold_rush_solver.py 541 || true 
python tfold_rush_solver.py 550 || true 
python tfold_rush_solver.py 552 || true 
python tfold_rush_solver.py 553 || true 
python tfold_rush_solver.py 557 || true 
python tfold_rush_solver.py 558 || true 
python tfold_rush_solver.py 562 || true 
python tfold_rush_solver.py 563 || true 
python tfold_rush_solver.py 564 || true 
python tfold_rush_solver.py 571 || true 
python tfold_rush_solver.py 572 || true 
python tfold_rush_solver.py 575 || true 
python tfold_rush_solver.py 578 || true 
python tfold_rush_solver.py 579 || true 
python tfold_rush_solver.py 580 || true 
python tfold_rush_solver.py 583 || true 
python tfold_rush_solver.py 585 || true 
python tfold_rush_solver.py 590 || true 
python tfold_rush_solver.py 596 || true 
python tfold_rush_solver.py 601 || true 
python tfold_rush_solver.py 602 || true 
python tfold_rush_solver.py 603 || true 
python tfold_rush_solver.py 606 || true 
python tfold_rush_solver.py 609 || true 
python tfold_rush_solver.py 612 || true 
python tfold_rush_solver.py 613 || true 
python tfold_rush_solver.py 615 || true 
python tfold_rush_solver.py 620 || true 
python tfold_rush_solver.py 621 || true 
python tfold_rush_solver.py 627 || true 
python tfold_rush_solver.py 628 || true 
python tfold_rush_solver.py 634 || true 
python tfold_rush_solver.py 637 || true 
python tfold_rush_solver.py 639 || true 
python tfold_rush_solver.py 640 || true 
python tfold_rush_solver.py 641 || true 
python tfold_rush_solver.py 644 || true 
python tfold_rush_solver.py 647 || true 
python tfold_rush_solver.py 650 || true 
python tfold_rush_solver.py 654 || true 
python tfold_rush_solver.py 657 || true 
python tfold_rush_solver.py 658 || true 
python tfold_rush_solver.py 660 || true 
python tfold_rush_solver.py 661 || true 
python tfold_rush_solver.py 665 || true 
python tfold_rush_solver.py 666 || true 
python tfold_rush_solver.py 667 || true 
python tfold_rush_solver.py 669 || true 
python tfold_rush_solver.py 678 || true 
python tfold_rush_solver.py 689 || true 
python tfold_rush_solver.py 692 || true 
python tfold_rush_solver.py 693 || true 
python tfold_rush_solver.py 697 || true 
python tfold_rush_solver.py 698 || true 
python tfold_rush_solver.py 706 || true 
python tfold_rush_solver.py 710 || true 
python tfold_rush_solver.py 711 || true 
python tfold_rush_solver.py 715 || true 
python tfold_rush_solver.py 716 || true 
python tfold_rush_solver.py 717 || true 
python tfold_rush_solver.py 718 || true 
python tfold_rush_solver.py 732 || true 
python tfold_rush_solver.py 749 || true 
python tfold_rush_solver.py 751 || true 
python tfold_rush_solver.py 753 || true 
python tfold_rush_solver.py 758 || true 
python tfold_rush_solver.py 762 || true 
python tfold_rush_solver.py 763 || true 
python tfold_rush_solver.py 766 || true 
python tfold_rush_solver.py 767 || true 
python tfold_rush_solver.py 772 || true 
python tfold_rush_solver.py 774 || true 
python tfold_rush_solver.py 777 || true 
python tfold_rush_solver.py 778 || true 
python tfold_rush_solver.py 779 || true 
python tfold_rush_solver.py 780 || true 
python tfold_rush_solver.py 782 || true 
python tfold_rush_solver.py 786 || true 
python tfold_rush_solver.py 787 || true 
python tfold_rush_solver.py 798 || true 
python tfold_rush_solver.py 806 || true 
python tfold_rush_solver.py 809 || true 
python tfold_rush_solver.py 810 || true 
python tfold_rush_solver.py 814 || true 
python tfold_rush_solver.py 816 || true 
python tfold_rush_solver.py 817 || true 
python tfold_rush_solver.py 819 || true 
python tfold_rush_solver.py 820 || true 
python tfold_rush_solver.py 823 || true 
python tfold_rush_solver.py 825 || true 
python tfold_rush_solver.py 831 || true 
python tfold_rush_solver.py 834 || true 
python tfold_rush_solver.py 847 || true 
python tfold_rush_solver.py 848 || true 
python tfold_rush_solver.py 856 || true 
python tfold_rush_solver.py 867 || true 
python tfold_rush_solver.py 869 || true 
python tfold_rush_solver.py 873 || true 
python tfold_rush_solver.py 881 || true 
python tfold_rush_solver.py 887 || true 
python tfold_rush_solver.py 888 || true 
python tfold_rush_solver.py 899 || true 
python tfold_rush_solver.py 900 || true 
python tfold_rush_solver.py 901 || true 
python tfold_rush_solver.py 909 || true 
python tfold_rush_solver.py 913 || true 
python tfold_rush_solver.py 921 || true 
python tfold_rush_solver.py 931 || true 
python tfold_rush_solver.py 936 || true 
python tfold_rush_solver.py 938 || true 
python tfold_rush_solver.py 945 || true 
python tfold_rush_solver.py 946 || true 
python tfold_rush_solver.py 957 || true 
python tfold_rush_solver.py 962 || true 
python tfold_rush_solver.py 970 || true 
python tfold_rush_solver.py 976 || true 
python tfold_rush_solver.py 977 || true 
python tfold_rush_solver.py 986 || true 
python tfold_rush_solver.py 988 || true 
python tfold_rush_solver.py 990 || true 
python tfold_rush_solver.py 992 || true 
python tfold_rush_solver.py 994 || true 
python tfold_rush_solver.py 996 || true 
python tfold_rush_solver.py 997 || true 
python tfold_rush_solver.py 1000 || true 
python tfold_rush_solver.py 1001 || true 
python tfold_rush_solver.py 1002 || true 
python tfold_rush_solver.py 1003 || true 
python tfold_rush_solver.py 1008 || true 
python tfold_rush_solver.py 1009 || true 
python tfold_rush_solver.py 1022 || true 
python tfold_rush_solver.py 1027 || true 
python tfold_rush_solver.py 1032 || true 
python tfold_rush_solver.py 1035 || true 
python tfold_rush_solver.py 1041 || true 
python tfold_rush_solver.py 1052 || true 
python tfold_rush_solver.py 1056 || true 
python tfold_rush_solver.py 1072 || true 
python tfold_rush_solver.py 1082 || true 
python tfold_rush_solver.py 1095 || true 
python tfold_rush_solver.py 1096 || true 
python tfold_rush_solver.py 1102 || true 
python tfold_rush_solver.py 1104 || true 
python tfold_rush_solver.py 1116 || true 
python tfold_rush_solver.py 1130 || true 
python tfold_rush_solver.py 1133 || true 
python tfold_rush_solver.py 1135 || true 
python tfold_rush_solver.py 1138 || true 
python tfold_rush_solver.py 1141 || true 
python tfold_rush_solver.py 1142 || true 
python tfold_rush_solver.py 1143 || true 
python tfold_rush_solver.py 1160 || true 
python tfold_rush_solver.py 1163 || true 
python tfold_rush_solver.py 1166 || true 
python tfold_rush_solver.py 1177 || true 
python tfold_rush_solver.py 1180 || true 
python tfold_rush_solver.py 1182 || true 
python tfold_rush_solver.py 1187 || true 
python tfold_rush_solver.py 1196 || true 
python tfold_rush_solver.py 1200 || true 
python tfold_rush_solver.py 1201 || true 
python tfold_rush_solver.py 1203 || true 
python tfold_rush_solver.py 1206 || true 
python tfold_rush_solver.py 1210 || true 
python tfold_rush_solver.py 1214 || true 
python tfold_rush_solver.py 1216 || true 
python tfold_rush_solver.py 1218 || true 
python tfold_rush_solver.py 1225 || true 
python tfold_rush_solver.py 1227 || true 
python tfold_rush_solver.py 1233 || true 
python tfold_rush_solver.py 1235 || true 
python tfold_rush_solver.py 1238 || true 
python tfold_rush_solver.py 1239 || true 
python tfold_rush_solver.py 1240 || true 
python tfold_rush_solver.py 1244 || true 
python tfold_rush_solver.py 1245 || true 
python tfold_rush_solver.py 1250 || true 
python tfold_rush_solver.py 1254 || true 
python tfold_rush_solver.py 1261 || true 
python tfold_rush_solver.py 1268 || true 
python tfold_rush_solver.py 1275 || true 
python tfold_rush_solver.py 1277 || true 
python tfold_rush_solver.py 1278 || true 
python tfold_rush_solver.py 1281 || true 
python tfold_rush_solver.py 1283 || true 
python tfold_rush_solver.py 1293 || true 
python tfold_rush_solver.py 1295 || true 
python tfold_rush_solver.py 1298 || true 
python tfold_rush_solver.py 1300 || true 
python tfold_rush_solver.py 1306 || true 
python tfold_rush_solver.py 1312 || true 
python tfold_rush_solver.py 1313 || true 
python tfold_rush_solver.py 1315 || true 
python tfold_rush_solver.py 1316 || true 
python tfold_rush_solver.py 1321 || true 
python tfold_rush_solver.py 1322 || true 
python tfold_rush_solver.py 1324 || true 
python tfold_rush_solver.py 1327 || true 
python tfold_rush_solver.py 1330 || true 
python tfold_rush_solver.py 1331 || true 
python tfold_rush_solver.py 1335 || true 
python tfold_rush_solver.py 1336 || true 
python tfold_rush_solver.py 1338 || true 
python tfold_rush_solver.py 1340 || true 
python tfold_rush_solver.py 1342 || true 
python tfold_rush_solver.py 1343 || true 
python tfold_rush_solver.py 1349 || true 
python tfold_rush_solver.py 1350 || true 
python tfold_rush_solver.py 1359 || true 
python tfold_rush_solver.py 1362 || true 
python tfold_rush_solver.py 1366 || true 
python tfold_rush_solver.py 1374 || true 
python tfold_rush_solver.py 1376 || true 
python tfold_rush_solver.py 1377 || true 
python tfold_rush_solver.py 1380 || true 
python tfold_rush_solver.py 1382 || true 
python tfold_rush_solver.py 1383 || true 
python tfold_rush_solver.py 1389 || true 
python tfold_rush_solver.py 1390 || true 
python tfold_rush_solver.py 1392 || true 
python tfold_rush_solver.py 1394 || true 
python tfold_rush_solver.py 1395 || true 
python tfold_rush_solver.py 1400 || true 
python tfold_rush_solver.py 1402 || true 
python tfold_rush_solver.py 1407 || true 
python tfold_rush_solver.py 1408 || true 
python tfold_rush_solver.py 1409 || true 
python tfold_rush_solver.py 1423 || true 
python tfold_rush_solver.py 1427 || true 
python tfold_rush_solver.py 1428 || true 
python tfold_rush_solver.py 1429 || true 
python tfold_rush_solver.py 1434 || true 
python tfold_rush_solver.py 1437 || true 
python tfold_rush_solver.py 1439 || true 
python tfold_rush_solver.py 1440 || true 
python tfold_rush_solver.py 1442 || true 
python tfold_rush_solver.py 1444 || true 
python tfold_rush_solver.py 1447 || true 
python tfold_rush_solver.py 1450 || true 
python tfold_rush_solver.py 1453 || true 
python tfold_rush_solver.py 1456 || true 
python tfold_rush_solver.py 1464 || true 
python tfold_rush_solver.py 1469 || true 
python tfold_rush_solver.py 1470 || true 
python tfold_rush_solver.py 1472 || true 
python tfold_rush_solver.py 1474 || true 
python tfold_rush_solver.py 1475 || true 
python tfold_rush_solver.py 1486 || true 
python tfold_rush_solver.py 1487 || true 
python tfold_rush_solver.py 1489 || true 
python tfold_rush_solver.py 1491 || true 
python tfold_rush_solver.py 1494 || true 
python tfold_rush_solver.py 1496 || true 
python tfold_rush_solver.py 1499 || true 
python tfold_rush_solver.py 1501 || true 
python tfold_rush_solver.py 1513 || true 
python tfold_rush_solver.py 1514 || true 
python tfold_rush_solver.py 1520 || true 
python tfold_rush_solver.py 1522 || true 
python tfold_rush_solver.py 1524 || true 
python tfold_rush_solver.py 1525 || true 
python tfold_rush_solver.py 1528 || true 
python tfold_rush_solver.py 1531 || true 
python tfold_rush_solver.py 1534 || true 
python tfold_rush_solver.py 1538 || true 
python tfold_rush_solver.py 1541 || true 
python tfold_rush_solver.py 1542 || true 
python tfold_rush_solver.py 1543 || true 
python tfold_rush_solver.py 1547 || true 
python tfold_rush_solver.py 1548 || true 
python tfold_rush_solver.py 1551 || true 
python tfold_rush_solver.py 1555 || true 
python tfold_rush_solver.py 1556 || true 
python tfold_rush_solver.py 1557 || true 
python tfold_rush_solver.py 1562 || true 
python tfold_rush_solver.py 1564 || true 
python tfold_rush_solver.py 1576 || true 
python tfold_rush_solver.py 1581 || true 
python tfold_rush_solver.py 1583 || true 
python tfold_rush_solver.py 1585 || true 
python tfold_rush_solver.py 1588 || true 
python tfold_rush_solver.py 1589 || true 
python tfold_rush_solver.py 1594 || true 
python tfold_rush_solver.py 1595 || true 
python tfold_rush_solver.py 1599 || true 
python tfold_rush_solver.py 1601 || true 
python tfold_rush_solver.py 1602 || true 
python tfold_rush_solver.py 1605 || true 
python tfold_rush_solver.py 1611 || true 
python tfold_rush_solver.py 1612 || true 
python tfold_rush_solver.py 1614 || true 
python tfold_rush_solver.py 1616 || true 
python tfold_rush_solver.py 1617 || true 
python tfold_rush_solver.py 1618 || true 
